### ISSUE TITLE
many function not found

### ISSUE THREAD

**Issue by zhouhesheng** [Keemotion/GPAC4iOS#1]
Undefined symbols for architecture x86_64:
  "_gf_sc_change_key_navigator", referenced from:
      _on_kn_set_focus in term_node_init.o
  "_gf_sc_del", referenced from:
      _gf_term_del in terminal.o
  "_gf_sc_draw_frame", referenced from:
      _MM_Loop in media_manager.o
      _gf_term_process_step in media_manager.o
      _gf_term_process_flush in media_manager.o
  "_gf_sc_get_av_caps", referenced from:
      _term_on_command in network_service.o
  "_gf_sc_get_clock", referenced from:
      _gf_term_get_time in terminal.o
  "_gf_sc_get_fps", referenced from:
      _gf_term_get_framerate in terminal.o
      _evaluate_term_cap in term_node_init.o
  "_gf_sc_get_offscreen_buffer", referenced from:
      _gf_term_get_offscreen_buffer in terminal.o
  "_gf_sc_get_option", referenced from:
      _gf_term_check_end_of_scene in terminal.o
      _gf_term_get_option in terminal.o
      _evaluate_term_cap in term_node_init.o
  "_gf_sc_get_screen_buffer", referenced from:
      _gf_term_get_screen_buffer in terminal.o
  "_gf_sc_get_selected_text", referenced from:
      _gf_term_get_text_selection in terminal.o
  "_gf_sc_get_viewpoint", referenced from:
      _gf_term_get_viewpoint in terminal.o
  "_gf_sc_has_text_selection", referenced from:
      _gf_term_get_text_selection in terminal.o
  "_gf_sc_invalidate", referenced from:
      _gf_term_invalidate_compositor in terminal.o
      _gf_term_on_node_modified in term_node_init.o
  "_gf_sc_key_navigator_del", referenced from:
      _TraverseKeyNavigator in term_node_init.o
  "_gf_sc_lock", referenced from:
      _gf_term_step_clocks in terminal.o
      _gf_term_handle_services in terminal.o
      _gf_term_queue_node_traverse in terminal.o
      _gf_term_unqueue_node_traverse in terminal.o
      _gf_term_lock_compositor in terminal.o
      _gf_term_play_from_time in terminal.o
      _gf_scene_force_size in scene.o
      ...
  "_gf_sc_map_point", referenced from:
      _gf_term_mouse_input in input_sensor.o
  "_gf_sc_new", referenced from:
      _gf_term_new in terminal.o
  "_gf_sc_next_frame_state", referenced from:
      _gf_term_step_clocks in terminal.o
  "_gf_sc_on_node_init", referenced from:
      _gf_term_on_node_init in term_node_init.o
  "_gf_sc_paste_text", referenced from:
      _gf_term_paste_text in terminal.o
  "_gf_sc_pick_node", referenced from:
      _gf_term_pick_node in terminal.o
  "_gf_sc_register_extra_graph", referenced from:
      _gf_scene_register_extra_graph in scene.o
  "_gf_sc_release_screen_buffer", referenced from:
      _gf_term_release_screen_buffer in terminal.o
  "_gf_sc_script_action", referenced from:
      _term_script_action in terminal.o
  "_gf_sc_set_fps", referenced from:
      _gf_term_new in terminal.o
      _gf_term_set_simulation_frame_rate in terminal.o
      _gf_term_set_speed in terminal.o
  "_gf_sc_set_option", referenced from:
      _gf_term_reload_cfg in terminal.o
      _gf_term_set_play_state in terminal.o
      _gf_term_set_option in terminal.o
      _gf_term_play_from_time in terminal.o
      _gf_scene_generate_views in scene.o
  "_gf_sc_set_scene", referenced from:
      _gf_scene_disconnect in scene.o
      _gf_scene_attach_to_compositor in scene.o
      _gf_scene_force_size in scene.o
      _gf_scene_regenerate in scene.o
      _gf_scene_generate_views in scene.o
  "_gf_sc_set_scene_size", referenced from:
      _gf_scene_force_size in scene.o
  "_gf_sc_set_size", referenced from:
      _gf_term_set_size in terminal.o
      _gf_scene_attach_to_compositor in scene.o
      _gf_scene_force_size in scene.o
  "_gf_sc_set_viewpoint", referenced from:
      _gf_term_set_viewpoint in terminal.o
  "_gf_sc_traverse_subscene", referenced from:
      _gf_inline_traverse in mpeg4_inline.o
  "_gf_sc_uri_is_hardcoded_proto", referenced from:
      _gf_inline_is_hardcoded_proto in mpeg4_inline.o
  "_gf_sc_use_raw_texture", referenced from:
      _gf_codec_add_channel in decoder.o
  "_gf_sc_user_event", referenced from:
      _gf_term_user_event in terminal.o
ld: symbol(s) not found for architecture x86_64

**Comment by cooler333** [comment]
+1

**Comment by AFcgi** [comment]
+1

**Comment by sriramios** [comment]
Any solution for this issue
